#!/usr/bin/env php
<?php
// application.php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use App\UpSlim;

// -----------------------------------------------------------------------------
// To help the built-in PHP dev server, check if the request was actually for
// something which should probably be served as a static file
// -----------------------------------------------------------------------------
if (PHP_SAPI === 'cli-server' && $_SERVER['SCRIPT_FILENAME'] !== __FILE__) {
    return false;
}

if (!defined('APP_DIR')):

    define('APP_DIR', __DIR__);

endif;
// -----------------------------------------------------------------------------
// Instantiate the app
// -----------------------------------------------------------------------------

$dotenv = new \Dotenv\Dotenv(__DIR__);

$dotenv->load();

$app = new \Flexe\App();

\Flexe\App::setInstance($app);


$application = new Application(\Flexe\App::getName(), \Flexe\App::getVersion());

Flexe\Console\Boot::setApplication($application);
Flexe\Console\Boot::bootCommand();

$application->run();